# action.yml
name: 'yewnorosen-sbom'
description: 'GitHub Action for publishing to RKVST SBOM Hub'
inputs:
  url: 
    description: 'RKVST URL'
    required: false
    default: 'https://app.rkvst.io'
  client-id:
    description: 'RKVST CLIENT_ID'
    required: true
  client-secret:
    description: 'RKVST CLIENT_SECRET'
    required: true
  publish:
    description: 'Publish SBOM publicly'
    required: false
    default: true
  format:
    description: 'SBOM Format'
    required: false
    default: 'cyclonedx-xml'
  sbom-files:
    description: 'SBOM File Paths'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --url${{inputs.url}}
    - --client_id${{inputs.client-id}}
    - --client_secret${{inputs.client-secret}}
    - --format${{inputs.format}}
    - --publish${{ inputs.publish }}
    - ${{ inputs.sbom-files }}
